chatterbox/urls.py
"""Defines URL patterns for chatterbox"""

from django.urls import path
from . import views

app_name = "chatterbox"
urlpatterns = [
    # Chat list page
    path("", views.chat_list, name="chat_list"),
    # Create chat page
    path("create_chat/", views.create_chat, name="create_chat"),
    # Private chat page
    path("chat/<str:username>/<str:other_username>/", views.chat, name="chat"),
    # Delete chat page
    path(
        "chat/<str:username>/<str:other_username>/delete_chat/",
        views.delete_chat,
        name="delete_chat",
    ),
    # Delete message page
    path(
        "delete_message/<int:message_id>/", views.delete_message, name="delete_message"
    ),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("chatterbox.urls")),
    path("user/", include("users.urls")),
]

users/urls.py
"""Defines URL patterns for users"""

from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    # Login page
    path(
        "login/",
        LoginView.as_view(template_name="registration/login.html"),
        name="login",
    ),
    # Registration page
    path("register/", views.register, name="register"),
    # Account page
    path("account/", views.account, name="account"),
    # Delete account page
    path("account/delete_account/", views.delete_account, name="delete_account"),
    # Logout page
    path("logout/", LogoutView.as_view(), name="logout"),
]

chatterbox/models.py
from datetime import datetime, timedelta, timezone
from django.contrib.auth.models import User
from django.db import models


class PrivateChat(models.Model):
    user1 = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="chats_user1"
    )
    user2 = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="chats_user2"
    )

    def __str__(self):
        return f"Chat between {self.user1.username} and {self.user2.username}"


class Message(models.Model):
    chat = models.ForeignKey(
        PrivateChat, on_delete=models.CASCADE, related_name="messages"
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(blank=True)
    image = models.BinaryField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def get_time_diff(self):
        if self.timestamp:
            now_time = datetime.now(timezone.utc)
            timediff = now_time - self.timestamp

            # Convert the timediff to human-readable format
            if timediff < timedelta(minutes=1):
                return f"{int(timediff.total_seconds())} seconds ago"
            elif timediff < timedelta(hours=1):
                return f"{int(timediff.total_seconds() // 60)} minutes ago"
            elif timediff < timedelta(days=1):
                return f"{int(timediff.total_seconds() // 3600)} hours ago"
            else:
                return f"{int(timediff.total_seconds() // 86400)} days ago"

    def __str__(self):
        if self.content:
            return f"{self.user.username}: {self.content[:20]}..."
        return f"{self.user.username} sent an image."

chatterbox/forms.py
from django import forms


class PrivateChatForm(forms.Form):
    username = forms.CharField(
        label="Username",
        max_length=100,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Enter username to chat"}
        ),
    )

chatterbox/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.models import User
from .models import PrivateChat, Message
from .forms import PrivateChatForm


@login_required
def chat_list(request):
    # Get all private chats involving the current user
    chats = PrivateChat.objects.filter(user1=request.user) | PrivateChat.objects.filter(
        user2=request.user
    )

    # Fetch the last message and time diff for each chat
    chats_with_last_messages = []
    for chat in chats:
        last_message = chat.messages.order_by("-timestamp").first()
        time_diff = last_message.get_time_diff() if last_message else "No messages yet"
        other_user = chat.user1 if chat.user2 == request.user else chat.user2
        chats_with_last_messages.append((other_user, last_message, time_diff))

    context = {"chats_with_last_messages": chats_with_last_messages}
    return render(request, "chatterbox/chat_list.html", context)


@login_required
def create_chat(request):
    if request.method == "POST":
        form = PrivateChatForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            other_user = User.objects.filter(username=username).first()

            if not other_user:
                messages.success(
                    request,
                    "The username you entered does not exist. Please try again.",
                )
                return redirect("chatterbox:create_chat")

            if other_user == request.user:
                messages.success(
                    request, "You cannot start a chat with yourself. Please try again."
                )
                return redirect("chatterbox:create_chat")

            # Fetch or create the chat
            chat, _ = (
                PrivateChat.objects.get_or_create(user1=request.user, user2=other_user)
                if request.user.id < other_user.id
                else PrivateChat.objects.get_or_create(
                    user1=other_user, user2=request.user
                )
            )

            return HttpResponseRedirect(
                reverse(
                    "chatterbox:chat", args=[request.user.username, other_user.username]
                )
            )

    else:
        form = PrivateChatForm()

    context = {"form": form}
    return render(request, "chatterbox/create_chat.html", context)


@login_required
def chat(request, username, other_username):
    user1 = get_object_or_404(User, username=username)
    user2 = get_object_or_404(User, username=other_username)

    if user1 == user2:
        return redirect("chatterbox:chat_list")

    if request.user == user1:
        # Fetch or create the chat
        chat, _ = (
            PrivateChat.objects.get_or_create(user1=user1, user2=user2)
            if user1.id < user2.id
            else PrivateChat.objects.get_or_create(user1=user2, user2=user1)
        )
    else:
        return redirect("chatterbox:chat_list")

    messages = Message.objects.filter(chat=chat).order_by("timestamp")

    # Zip with previous message
    messages_with_prev = []
    prev = None
    for message in messages:
        messages_with_prev.append((message, prev))
        prev = message

    context = {
        "messages_with_prev": messages_with_prev,
        "current_user": user1,
        "other_user": user2,
    }
    return render(request, "chatterbox/chat.html", context)


@login_required
def delete_chat(request, username, other_username):
    try:
        user1 = User.objects.get(username=username)
        user2 = User.objects.get(username=other_username)
        # Determine the correct order for user1 and user2 in the chat
        chat = (
            PrivateChat.objects.get(user1=user1, user2=user2)
            if user1.id < user2.id
            else PrivateChat.objects.get(user1=user2, user2=user1)
        )
        chat.delete()
        messages.success(request, "Chat has been successfully deleted!")
    except User.DoesNotExist:
        messages.error(request, "One or both users do not exist.")
    except PrivateChat.DoesNotExist:
        messages.error(request, "Chat does not exist.")
    except Exception as err:
        messages.error(request, "An unexpected error occurred.")
        print(f"Unexpected error: {err}")

    return redirect("chatterbox:chat_list")


@login_required
def delete_message(request, message_id):
    message = get_object_or_404(Message, id=message_id)
    message.delete()

    chat = message.chat
    current_user = request.user
    other_user = chat.user2 if chat.user1 == request.user else chat.user1

    return redirect(
        "chatterbox:chat",
        username=current_user.username,
        other_username=other_user.username,
    )

chatterbox/templates/chatterbox/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">

    <!-- Webpage title -->
    <title>Chatterbox - {% block title %}{% endblock title %}</title>

    <!-- Bootstrap CSS -->
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <!-- Custom styles -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'main.css' %}">

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.png' %}">
</head>

<body>
    <!-- navbar start -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'chatterbox:chat_list' %}">Chatterbox</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == '/' %}active{% endif %}" aria-current="page" href="{% url 'chatterbox:chat_list' %}"><i class="bi bi-chat-dots me-2"></i>All Chats</a>
                        </li>
                    {% endif %}
                </ul>

                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == '/account/' %}active{% endif %}" href="{% url 'users:account' %}"><i class="bi bi-gear me-2"></i>Account Settings</a>
                        </li>
                        <li class="nav-item">
                            <form action="{% url 'users:logout' %}" method="POST" class="d-inline">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger ms-lg-3"><i class="bi bi-box-arrow-right me-2"></i>Log out</button>
                            </form>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == '/user/login/' %}active{% endif %}" href="{% url 'users:login' %}"><i class="bi bi-door-open me-2"></i>Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link ms-lg-3 {% if request.path == '/user/register/' %}active{% endif %}" href="{% url 'users:register' %}"><i class="bi bi-person me-2"></i>Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <!-- navbar end -->

    <main role="main" class="container mt-lg-5 mt-3">
        <!-- custom content start -->
        {% block content %}{% endblock %}
        <!-- custom content end -->
    </main>

    <!-- custom footer start -->
    {% block footer %}{% endblock footer %}
    <!-- custom footer end -->
</body>

</html>

chatterbox/templates/chatterbox/chat.html
{% extends "chatterbox/base.html" %}
{% load chatterbox_filters %}
{% load user_filters %}
{% load static %}

{% block title %}{{ other_user.username }}{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <!-- Fixed height for the card -->
                <div class="card shadow-sm" style="height: 600px;">
                    <div class="card-body d-flex flex-column" style="height: 100%;">
                        <!-- chat deletion -->
                        <div class="d-flex justify-content-end mb-3">
                            <form action="{% url 'chatterbox:delete_chat' username=current_user other_username=other_user %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger"><i class="bi bi-trash"></i></button>
                            </form>
                        </div>

                        <!-- chat messages -->
                        <div id="messages-container" class="pt-3 pe-3 messages-container flex-grow-1 overflow-auto">
                            {% for message, prev in messages_with_prev  %}
                                {% if prev and message.timestamp.date != prev.timestamp.date %}
                                    <p class="text-center text-muted">{{ message.timestamp.date }}</p>
                                {% endif %}
                                {% if message.user == request.user %}
                                    <!-- message from the signed-in user (align right) -->
                                    <div class="d-flex flex-row justify-content-end mb-3">
                                        <div class="me-2">
                                            {% if message.content %}
                                                <p class="small p-2 mb-1 rounded-3 bg-primary text-white {{ message.content|update_bg_color }}">
                                                    {{ message.content|make_links|safe }}
                                                </p>
                                            {% endif %}
                                            {% if message.image %}
                                                <img src="data:image/png;base64,{{ message.image|base64 }}" class="img-fluid rounded mb-1" style="max-width: 200px;"/>
                                            {% endif %}
                                            <p class="small mb-0 rounded-3 text-muted text-end">{{ message.timestamp|date:"h:i A" }}</p>
                                        </div>

                                        <!-- dropdown button for message actions -->
                                        <div class="dropdown">
                                            <button class="btn btn-sm btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false"></button>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <form action="{% url 'chatterbox:delete_message' message.id %}" method="POST">
                                                        {% csrf_token %}
                                                        <button type="submit" class="dropdown-item text-danger">
                                                            <i class="bi bi-x-circle"></i> Delete message
                                                        </button>
                                                    </form>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                {% else %}
                                    <!-- message from the other user (align left) -->
                                    <div class="d-flex flex-row justify-content-start mb-3">
                                        <div class="ms-2">
                                            {% if message.content %}
                                                <p class="small p-2 mb-1 rounded-3 bg-secondary text-white {{ message.content|update_bg_color }}">
                                                    {{ message.content|make_links|safe }}
                                                </p>
                                            {% endif %}
                                            {% if message.image %}
                                                <img src="data:image/png;base64,{{ message.image|base64 }}" class="img-fluid rounded mb-1" style="max-width: 200px;"/>
                                            {% endif %}
                                            <p class="small mb-0 rounded-3 text-muted">{{ message.timestamp|date:"h:i A" }}</p>
                                        </div>
                                    </div>
                                {% endif %}
                            {% empty %}
                                <div class="alert alert-info text-center">No messages yet.</div>
                            {% endfor %}
                        </div>

                        <!-- message input area, stays at the bottom -->
                        <div class="d-flex align-items-center mt-3">
                            {% if current_user.profile.avatar %}
                                <img src="data:image/png;base64,{{ current_user.profile.avatar|base64 }}" id="avatar" alt="avatar" class="rounded-circle"/>
                            {% else %}
                                <img src="{% static 'default.png' %}" id="avatar" alt="avatar" class="rounded-circle"/>
                            {% endif %}
                            <input type="file" id="image_input" class="form-control-file ms-2" accept="image/*" style="display: none;"/>
                            <input type="text" id="message_send_input" class="form-control form-control-lg ms-2" placeholder="Type message" autofocus>
                            <button id="image_send_button" class="btn btn-secondary ms-2"><i class="bi bi-image"></i></button>
                            <button id="message_send_button" class="btn btn-primary ms-2"><i class="bi bi-send"></i></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Hidden input fields to store usernames for JavaScript -->
    <input type="hidden" id="username" value="{{ user.username }}">
    <input type="hidden" id="otherUsername" value="{{ other_user.username }}">

    <!-- Custom JavaScript -->
    <script type="module" src="{% static 'js/utils.js' %}"></script>
    <script type="module" src="{% static 'js/file_upload.js' %}"></script>
    <script type="module" src="{% static 'js/chat.js' %}"></script>

{% endblock content %}

{% block footer %}
    <!-- footer start -->
    <footer class="border-top border-dark mt-5">
        <p class="text-center text-body-dark mt-3">&copy; 2024 KafetzisThomas</p>
    </footer>
    <!-- footer end -->
{% endblock footer %}

chatterbox/templates/chatterbox/chat_list.html
{% extends "chatterbox/base.html" %}
{% load user_filters %}
{% load static %}

{% block title %}Chats{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-success" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="card shadow-sm">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h4 class="mb-0">Chats</h4>
                        <a href="{% url 'chatterbox:create_chat' %}" class="btn btn-secondary"><i class="bi bi-pencil"></i></a>
                    </div>
                    <div class="card-body">
                        <div class="profile-container">
                            <ul class="list-unstyled mb-0">
                                {% for other_user, last_message, time_diff in chats_with_last_messages %}
                                    {% if request.user != other_user %}
                                        <li class="p-3 border-bottom">
                                            <a href="{% url 'chatterbox:chat' username=request.user.username other_username=other_user.username %}" class="d-flex align-items-center text-decoration-none text-dark">
                                                {% if other_user.profile.avatar %}
                                                    <img src="data:image/png;base64,{{ other_user.profile.avatar|base64 }}" alt="avatar1" class="rounded-circle me-3" width="60" height="60" style="object-fit: cover;"/>
                                                {% else %}
                                                    <img src="{% static 'default.png' %}" alt="avatar1" class="rounded-circle me-3" width="60"/>
                                                {% endif %}
                                                <div class="flex-grow-1">
                                                    <p class="fw-bold mb-0">{{ other_user.username }}</p>
                                                    <p class="small text-muted mb-0">
                                                        {% if last_message %}
                                                            {{ last_message.content }}
                                                        {% else %}
                                                            No messages yet.
                                                        {% endif %}
                                                    </p>
                                                </div>
                                                <div class="text-muted small ms-3">
                                                    <p class="mb-0">{{ time_diff }}</p>
                                                </div>
                                            </a>
                                        </li>
                                    {% endif %}
                                {% empty %}
                                    <li class="text-center py-3"><h4>No chats yet.</h4></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block footer %}
    <!-- footer start -->
    <footer class="border-top border-dark mt-5 fixed-bottom">
        <p class="text-center text-body-dark mt-3">&copy; 2024 KafetzisThomas</p>
    </footer>
    <!-- footer end -->
{% endblock footer %}

chatterbox/templates/chatterbox/create_chat.html
{% extends "chatterbox/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create Chat{% endblock title %}

{% block content %}
    <div class="container">
        <h1 class="mb-4 text-center">Create Chat</h1>
        <div class="row justify-content-center">
            <div class="col-md-8 col-lg-6">
                <form method="POST" action="{% url 'chatterbox:create_chat' %}" class="bg-light p-4 rounded shadow-sm">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-danger">{{ message }}</div>
                        {% endfor %}
                    {% endif %}
                    
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="text-center mt-3">
                        <button type="submit" class="btn btn-primary">Create Chat</button>
                    </div>
                    <input type="hidden" name="next" value="{% url 'chatterbox:chat_list' %}" />
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

{% block footer %}
    <!-- footer start -->
    <footer class="border-top border-dark mt-5 fixed-bottom">
        <p class="text-center text-body-dark mt-3">&copy; 2024 KafetzisThomas</p>
    </footer>
    <!-- footer end -->
{% endblock footer %}