chatterbox/urls.py
"""Defines URL patterns for chatterbox"""

from django.urls import path
from . import views

app_name = "chatterbox"
urlpatterns = [
    # Chat list page
    path("", views.chat_list, name="chat_list"),
    # Create chat page
    path("create_chat/", views.create_chat, name="create_chat"),
    # Private chat page
    path("chat/<str:username>/<str:other_username>/", views.chat, name="chat"),
    # Delete chat page
    path(
        "chat/<str:username>/<str:other_username>/delete_chat/",
        views.delete_chat,
        name="delete_chat",
    ),
    # Delete message page
    path(
        "delete_message/<int:message_id>/", views.delete_message, name="delete_message"
    ),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("chatterbox.urls")),
    path("user/", include("users.urls")),
]

users/urls.py
"""Defines URL patterns for users"""

from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    # Login page
    path(
        "login/",
        LoginView.as_view(template_name="registration/login.html"),
        name="login",
    ),
    # Registration page
    path("register/", views.register, name="register"),
    # Account page
    path("account/", views.account, name="account"),
    # Delete account page
    path("account/delete_account/", views.delete_account, name="delete_account"),
    # Logout page
    path("logout/", LogoutView.as_view(), name="logout"),
]

users/models.py
import io
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    """
    Extending User model by adding an avatar stored as bytes.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.BinaryField(blank=True, null=True)

    def save(self, *args, **kwargs):
        """
        Resize the avatar image.
        Convert it to bytes.
        """
        if self.avatar:
            img = Image.open(io.BytesIO(self.avatar))
            if img.height > 300 or img.width > 300:
                new_img = (300, 300)
                img.thumbnail(new_img)

            byte_io = io.BytesIO()
            img.save(byte_io, format="PNG")
            self.avatar = byte_io.getvalue()

        super().save(*args, **kwargs)

    def __str__(self):
        return self.user.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from .models import Profile


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(
        label="Email Address", widget=forms.EmailInput, required=True
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class UpdateUserForm(forms.ModelForm):
    email = forms.EmailField(
        label="Email Address", widget=forms.EmailInput, required=True
    )
    password1 = forms.CharField(
        label="New Password", widget=forms.PasswordInput, required=False
    )
    password2 = forms.CharField(
        label="Confirm New Password", widget=forms.PasswordInput, required=False
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password1 != password2:
            self.add_error("password2", "Passwords do not match.")

        if password1:
            try:
                validate_password(password1)
            except ValidationError as e:
                self.add_error("password1", e)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password1")
        if password:
            user.set_password(password)
        if commit:
            user.save()
        return user


class UpdateProfileForm(forms.ModelForm):
    avatar = forms.ImageField(required=False)

    class Meta:
        model = Profile
        fields = []

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, UpdateUserForm, UpdateProfileForm
from django.contrib.auth.models import User
from django.contrib import messages


def register(request):
    """
    Register a new user.
    """
    if request.method == "POST":
        form = CustomUserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, "Account successfully created! You're now able to login."
            )
            return redirect("users:login")
    else:
        form = CustomUserCreationForm()

    context = {"form": form}
    return render(request, "registration/register.html", context)


@login_required
def account(request):
    if request.method == "POST":
        user_form = UpdateUserForm(instance=request.user, data=request.POST)
        profile_form = UpdateProfileForm(
            instance=request.user.profile, data=request.POST, files=request.FILES
        )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()

            # Save the profile form with the updated avatar as byte data
            profile = profile_form.save(commit=False)
            avatar_file = profile_form.cleaned_data.get("avatar")
            if avatar_file:
                avatar_bytes = avatar_file.read()
                profile.avatar = avatar_bytes

            profile.save()

            update_session_auth_hash(request, request.user)  # Keep user logged in
            messages.success(
                request, "Your account settings were successfully updated!"
            )
            return redirect("chatterbox:chat_list")
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)

    context = {
        "user_form": user_form,
        "profile_form": profile_form,
    }
    return render(request, "users/account.html", context)


@login_required
def delete_account(request):
    user = User.objects.get(id=request.user.id)
    user.delete()
    messages.error(request, "Your account has been successfully deleted!")
    return redirect("users:register")

users/templates/users/account.html
{% extends "chatterbox/base.html" %}
{% load crispy_forms_tags %}
{% load user_filters %}
{% load static %}

{% block title %}Account{% endblock title %}

{% block content %}
    <div class="container mb-4">
        <h1 class="mb-4 text-center">Your Account Settings</h1>
        <div class="row justify-content-center">
            <div class="col-md-8 col-lg-6">
                <form method="POST" action="{% url 'users:account' %}" enctype="multipart/form-data" class="bg-white p-4 rounded shadow-sm">
                    {% csrf_token %}
                    <!-- profile picture -->
                    <div class="text-center mb-4">
                        <div class="position-relative d-inline-block">
                            {% if user.profile.avatar %}
                                <img class="rounded-circle border border-secondary shadow-sm mb-2" src="data:image/png;base64,{{ user.profile.avatar|base64 }}" alt="{{ user.username }}'s avatar" style="width: 150px; height: 150px; object-fit: cover; cursor: pointer;"/>
                            {% else %}
                                <img class="rounded-circle border border-secondary shadow-sm mb-2" src="{% static 'default.png' %}" alt="{{ user.username }}'s avatar" style="width: 150px; height: 150px; object-fit: cover; cursor: pointer;"/>
                            {% endif %}
                        </div>
                    </div>

                    <!-- form fields -->
                    {{ user_form|crispy }}
                    {{ profile_form|crispy }}

                    <!-- save & delete buttons -->
                    <div class="text-center mt-4">
                        <button name="submit" class="btn btn-primary me-2 mb-lg-0 mb-2"><i class="bi bi-floppy"></i> Save Changes</button>
                        <a class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete_account_modal" role="button"><i class="bi bi-trash"></i> Delete Account</a>
                    </div>
                    <input type="hidden" name="next" value="{% url 'chatterbox:chat_list' %}" />
                </form>
            </div>
        </div>
    </div>

    <!-- Delete account modal start -->
    <div class="modal fade" id="delete_account_modal" tabindex="-1" aria-labelledby="delete_account_modal_label" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="delete_account_modal_label">DELETE ACCOUNT</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Procceed below to delete your account and all associated data. Deleting your account is permanent. It cannot be undone.
                </div>
                <div class="modal-footer">
                    <a class="btn btn-danger" href="{% url 'users:delete_account' %}" role="button">Delete account</a>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Delete account modal end -->
{% endblock content %}

{% block footer %}
    <!-- footer start -->
    <footer class="border-top border-dark mt-5">
        <p class="text-center text-body-dark mt-3">&copy; 2024 KafetzisThomas</p>
    </footer>
    <!-- footer end -->
{% endblock footer %}